name: Schedule Workflow
on: 
  schedule:
    - cron: '0 0 1 1 *'
jobs:
  scheduled_job: 
    runs-on: ubuntu-latest
    steps:
      - name: Scheduled Triggered
        run: echo "This job runs on a schedule! every 5 minutes"